### ISSUE TITLE
Question on project status

### ISSUE THREAD

**Issue by chiehminwei** [jamerst/JobHunt#1]
Hello this looks amazing.
A few quick questions:

1. Does it only support searching from Indeed?
2. Could you explain at a high level how is searching done? If you crawl Indeed at a specified interval, do you have to define your search term upfront, and only search results relevant to those terms will get crawled and updated?
3. What search features do you support? Is it only by name and distance?
4. In the search results, do you have the job description and application link?

**Comment by jamerst** [comment]
Hi,

I didn't actually expect anyone to find this useful, it's just a pet project really, but feel free to give it a try if you think it might be!

1. Currently only Indeed is supported (though the architecture is designed to support searching other platforms). Whether support for a given platform can be added depends on the specific platform. I've stuck with Indeed because there are reliable APIs available, if a platform can only be searched by scraping it's more work and probably less reliable.
2. For Indeed new jobs are fetched on a configurable schedule (3 times per day at 9am, 12pm and 6pm by default). Jobs are found using the undocumented GraphQL API. Searches are pre-configured - the main use case for JobHunt is to consolidate jobs from multiple searches into a single source (e.g. searches for different job titles or locations).
3. It supports searching by job title/keyword, location, and distance from location.
4. Yes, the job title, description, salary (if available) and location are stored. Indeed also has "tags" for each job which aren't displayed publicly, these are used to automatically categorise jobs to an extent. A link to the job posting on Indeed is stored for jobs fetched from Indeed.

**Comment by jamerst** [comment]
The jobs from Indeed are stored locally in a Postgres database, so you could filter those in more advanced ways than Indeed allows natively.

I think you will probably run into issues trying to scale it up though. The API used is entirely undocumented and unofficial, so I'm not sure what rate limits are in place, if any. An API key is needed to use it which is associated with your own Indeed account, so if you had a large number of searches covering large areas refreshed frequently I imagine they would catch on to the high usage pretty quickly.

This is why JobHunt is designed to be self-hosted - it's just not really scalable given the nature of the APIs used. Building something bigger that uses the data fetched from Indeed indirectly is possible, but the problem of getting a sufficient volume of data still remains.

**Comment by chiehminwei** [comment]
That makes a lot of sense -- thank you so much!
